# Node.js with Vue

# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run test:unit
  displayName: 'unit tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './test-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Unit tests'
    
- script: |
    mkdir ./tests/e2e/reports/
    npm run test:e2e
  displayName: 'e2e tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './tests/e2e/reports/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'e2e Tests'

- script: npm run build
  displayName: 'npm build'
